import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

caracteristiques = pd.read_csv("carcteristiques-2022.csv", sep=";").rename(columns={"Accident_Id": "Num_Acc"})


caracteristiques["lum"] = caracteristiques["lum"].replace(1, "Plein jour")
caracteristiques["lum"] = caracteristiques["lum"].replace(2, "Crépuscule ou aube")
caracteristiques["lum"] = caracteristiques["lum"].replace(3, "Nuit sans éclairage public")
caracteristiques["lum"] = caracteristiques["lum"].replace(4, "Nuit avec éclairage public non allumé")
caracteristiques["lum"] = caracteristiques["lum"].replace(5, "Nuit avec éclairage public allumé")

caracteristiques["agg"] = caracteristiques["agg"].replace(1, "Hors agglomération")
caracteristiques["agg"] = caracteristiques["agg"].replace(2, "En agglomération")

caracteristiques["int"] = caracteristiques["int"].replace(1, "Hors intersection")
caracteristiques["int"] = caracteristiques["int"].replace(2, "Intersection en X")
caracteristiques["int"] = caracteristiques["int"].replace(3, "Intersection en T")
caracteristiques["int"] = caracteristiques["int"].replace(4, "Intersection en Y")
caracteristiques["int"] = caracteristiques["int"].replace(5, "Intersection à plus de 4 branches")
caracteristiques["int"] = caracteristiques["int"].replace(6, "Giratoire")
caracteristiques["int"] = caracteristiques["int"].replace(7, "Place")
caracteristiques["int"] = caracteristiques["int"].replace(8, "Passage à niveau")
caracteristiques["int"] = caracteristiques["int"].replace(9, "Autre intersection")

caracteristiques["atm"] = caracteristiques["atm"].replace(1, "Normale")
caracteristiques["atm"] = caracteristiques["atm"].replace(2, "Pluie légère")
caracteristiques["atm"] = caracteristiques["atm"].replace(3, "Pluie forte")
caracteristiques["atm"] = caracteristiques["atm"].replace(4, "Neige - grêle")
caracteristiques["atm"] = caracteristiques["atm"].replace(5, "Brouillard - fumée")
caracteristiques["atm"] = caracteristiques["atm"].replace(6, "Vent fort - tempête")
caracteristiques["atm"] = caracteristiques["atm"].replace(7, "Temps éblouissant")
caracteristiques["atm"] = caracteristiques["atm"].replace(8, "Temps couvert")
caracteristiques["atm"] = caracteristiques["atm"].replace(9, "Autre")

caracteristiques = caracteristiques[caracteristiques["atm"] != -1]

caracteristiques["col"] = caracteristiques["col"].replace(1, "Deux véhicules - frontale")
caracteristiques["col"] = caracteristiques["col"].replace(2, "Deux véhicules - par l'arrière")
caracteristiques["col"] = caracteristiques["col"].replace(3, "Deux véhicules - par le côté")
caracteristiques["col"] = caracteristiques["col"].replace(4, "Trois véhicules et plus - en chaîne")
caracteristiques["col"] = caracteristiques["col"].replace(5, "Trois véhicules et plus - collisions multiples")
caracteristiques["col"] = caracteristiques["col"].replace(6, "Autre collision")
caracteristiques["col"] = caracteristiques["col"].replace(7, "Sans collision")


lieux = pd.read_csv("lieux-2022.csv", sep=";").rename(columns={"Accident_Id": "Num_Acc"})

lieux = lieux.dropna(axis=1, thresh=0.8*len(lieux))

lieux["catr"] = lieux["catr"].replace(1, "Autoroute")
lieux["catr"] = lieux["catr"].replace(2, "Route Nationale")
lieux["catr"] = lieux["catr"].replace(3, "Route Départementale")
lieux["catr"] = lieux["catr"].replace(4, "Voie Communale")
lieux["catr"] = lieux["catr"].replace(5, "Hors réseau public")
lieux["catr"] = lieux["catr"].replace(6, "Parc de stationnement ouvert à la circulation publique")
lieux["catr"] = lieux["catr"].replace(7, "Routes de métropole urbaine")
lieux["catr"] = lieux["catr"].replace(9, "Autre")

lieux["circ"] = lieux["circ"].replace(-1, "Non renseigné")
lieux["circ"] = lieux["circ"].replace(1, "A sens unique")
lieux["circ"] = lieux["circ"].replace(2, "Bidirectionnelle")
lieux["circ"] = lieux["circ"].replace(3, "A chaussées séparées")
lieux["circ"] = lieux["circ"].replace(4, "Avec voies d'affectation variable")

lieux["vosp"] = lieux["vosp"].replace(-1, "Non renseigné")
lieux["vosp"] = lieux["vosp"].replace(0, "Sans objet")
lieux["vosp"] = lieux["vosp"].replace(1, "Piste cyclable")
lieux["vosp"] = lieux["vosp"].replace(2, "Bande cyclable")
lieux["vosp"] = lieux["vosp"].replace(3, "Voie réservée")

lieux["prof"] = lieux["prof"].replace(-1, "Non renseigné")
lieux["prof"] = lieux["prof"].replace(1, "Plat")
lieux["prof"] = lieux["prof"].replace(2, "Pente")
lieux["prof"] = lieux["prof"].replace(3, "Sommet de côte")
lieux["prof"] = lieux["prof"].replace(4, "Bas de côte")

lieux["plan"] = lieux["plan"].replace(-1, "Non renseigné")
lieux["plan"] = lieux["plan"].replace(1, "Partie rectiligne")
lieux["plan"] = lieux["plan"].replace(2, "En courbe à gauche")
lieux["plan"] = lieux["plan"].replace(3, "En courbe à droite")
lieux["plan"] = lieux["plan"].replace(4, "En « S »")

lieux["surf"] = lieux["surf"].replace(-1, "Non renseigné")
lieux["surf"] = lieux["surf"].replace(1, "Normale")
lieux["surf"] = lieux["surf"].replace(2, "Mouillée")
lieux["surf"] = lieux["surf"].replace(3, "Flaques")
lieux["surf"] = lieux["surf"].replace(4, "Inondée")
lieux["surf"] = lieux["surf"].replace(5, "Enneigée")
lieux["surf"] = lieux["surf"].replace(6, "Boue")
lieux["surf"] = lieux["surf"].replace(7, "Verglacée")
lieux["surf"] = lieux["surf"].replace(8, "Corps gras - huile")
lieux["surf"] = lieux["surf"].replace(9, "Autre")

lieux["infra"] = lieux["infra"].replace(-1, "Non renseigné")
lieux["infra"] = lieux["infra"].replace(0, "Aucune")
lieux["infra"] = lieux["infra"].replace(1, "Souterrain - tunnel")
lieux["infra"] = lieux["infra"].replace(2, "Pont - autopont")
lieux["infra"] = lieux["infra"].replace(3, "Bretelle d'échangeur")
lieux["infra"] = lieux["infra"].replace(4, "Voie ferrée")
lieux["infra"] = lieux["infra"].replace(5, "Carrefour aménagé")
lieux["infra"] = lieux["infra"].replace(6, "Zone piétonne")
lieux["infra"] = lieux["infra"].replace(7, "Zone de péage")
lieux["infra"] = lieux["infra"].replace(8, "Chantier")
lieux["infra"] = lieux["infra"].replace(9, "Autre")

lieux["situ"] = lieux["situ"].replace(-1, "Non renseigné")
lieux["situ"] = lieux["situ"].replace(0, "Aucun")
lieux["situ"] = lieux["situ"].replace(1, "Sur chaussée")
lieux["situ"] = lieux["situ"].replace(2, "Sur bande d'arrêt d'urgence")
lieux["situ"] = lieux["situ"].replace(3, "Sur accotement")
lieux["situ"] = lieux["situ"].replace(4, "Sur trottoir")
lieux["situ"] = lieux["situ"].replace(5, "Sur piste cyclable")
lieux["situ"] = lieux["situ"].replace(6, "Sur autre voie spéciale")
lieux["situ"] = lieux["situ"].replace(8, "Autres")

vehicules = pd.read_csv("vehicules-2022.csv", sep=";").rename(columns={"Accident_Id": "Num_Acc"})


vehicules["senc"] = vehicules["senc"].replace(-1, "Non renseigné")
vehicules["senc"] = vehicules["senc"].replace(0, "Inconnu")
vehicules["senc"] = vehicules["senc"].replace(1, "PK ou PR ou numéro d'adresse postale croissant")
vehicules["senc"] = vehicules["senc"].replace(2, "PK ou PR ou numéro d'adresse postale décroissant")
vehicules["senc"] = vehicules["senc"].replace(3, "Absence de repère")

vehicules["catv"] = vehicules["catv"].replace(0, "Indéterminable")
vehicules["catv"] = vehicules["catv"].replace(1, "Bicyclette")
vehicules["catv"] = vehicules["catv"].replace(2, "Cyclomoteur <50cm3")
vehicules["catv"] = vehicules["catv"].replace(3, "Voiturette (Quadricycle à moteur carrossé) (anciennement " "voiturette ou tricycle à moteur)")
vehicules["catv"] = vehicules["catv"].replace(4, "Référence inutilisée depuis 2006 (scooter immatriculé)")
vehicules["catv"] = vehicules["catv"].replace(5, "Référence plus en usage depuis 2006 (Motocyclette)")
vehicules["catv"] = vehicules["catv"].replace(6, "Référence plus en usage depuis 2006 (Side-car)")
vehicules["catv"] = vehicules["catv"].replace(7, "VL seul")
vehicules["catv"] = vehicules["catv"].replace(8, "Référence inutilisée depuis 2006 (VL + caravane)")
vehicules["catv"] = vehicules["catv"].replace(9, "Référence inutilisée depuis 2006 (VL + remorque)")
vehicules["catv"] = vehicules["catv"].replace(10, "VU seul 1,5T <= PTAC <= 3,5T avec ou sans remorque (anciennement VU seul 1,5T <= PTAC <= 3,5T)")
vehicules["catv"] = vehicules["catv"].replace(11, "Référence inutilisée depuis 2006 (VU (10) + caravane)")
vehicules["catv"] = vehicules["catv"].replace(12, "Référence inutilisée depuis 2006 (VU (10) + remorque)")
vehicules["catv"] = vehicules["catv"].replace(13, "PL seul 3,5T <PTCA <= 7,5T")
vehicules["catv"] = vehicules["catv"].replace(14, "PL seul > 7,5T")
vehicules["catv"] = vehicules["catv"].replace(15, "PL > 3,5T + remorque")
vehicules["catv"] = vehicules["catv"].replace(16, "Tracteur routier seul")
vehicules["catv"] = vehicules["catv"].replace(17, "Tracteur routier + semi-remorque")
vehicules["catv"] = vehicules["catv"].replace(18, "Référence inutilisée depuis 2006 (transport en commun)")
vehicules["catv"] = vehicules["catv"].replace(19, "Référence inutilisée depuis 2006 (tramway)")
vehicules["catv"] = vehicules["catv"].replace(20, "Engin spécial")
vehicules["catv"] = vehicules["catv"].replace(21, "Tracteur agricole")
vehicules["catv"] = vehicules["catv"].replace(30, "Scooter < 50 cm3")
vehicules["catv"] = vehicules["catv"].replace(31, "Motocyclette > 50 cm et <= 125 cm")
vehicules["catv"] = vehicules["catv"].replace(32, "Scooter > 50 cm et <= 125 cm")
vehicules["catv"] = vehicules["catv"].replace(33, "Motocyclette > 125 cm3")
vehicules["catv"] = vehicules["catv"].replace(34, "Scooter > 125 cm3")
vehicules["catv"] = vehicules["catv"].replace(35, "Quad léger <= 50 cm (Quadricycle à moteur non carrossé)")
vehicules["catv"] = vehicules["catv"].replace(36, "Quad lourd > 50 cm (Quadricycle à moteur non carrossé)")
vehicules["catv"] = vehicules["catv"].replace(37, "Autobus")
vehicules["catv"] = vehicules["catv"].replace(38, "Autocar")
vehicules["catv"] = vehicules["catv"].replace(39, "Train")
vehicules["catv"] = vehicules["catv"].replace(40, "Tramway")
vehicules["catv"] = vehicules["catv"].replace(41, "3RM <= 50cm3")
vehicules["catv"] = vehicules["catv"].replace(42, "3RM > 50cm3 et <= 125cm3")
vehicules["catv"] = vehicules["catv"].replace(43, "3RM > 125cm3")
vehicules["catv"] = vehicules["catv"].replace(44, "EDP à moteur")
vehicules["catv"] = vehicules["catv"].replace(45, "EDP sans moteur 80 - VAE")
vehicules["catv"] = vehicules["catv"].replace(99, "Autre véhicule")

vehicules["obs"] = vehicules["obs"].replace(0, "Sans objet")
vehicules["obs"] = vehicules["obs"].replace(1, "Véhicule en stationnement")
vehicules["obs"] = vehicules["obs"].replace(2, "Arbre")
vehicules["obs"] = vehicules["obs"].replace(3, "Glissière métallique")
vehicules["obs"] = vehicules["obs"].replace(4, "Glissière béton")
vehicules["obs"] = vehicules["obs"].replace(5, "Autre glissière")
vehicules["obs"] = vehicules["obs"].replace(6, "Bâtiment, mur, pile de pont")
vehicules["obs"] = vehicules["obs"].replace(7, "Support de signalisation verticale ou poste d'appel d'urgence")
vehicules["obs"] = vehicules["obs"].replace(8, "Poteau")
vehicules["obs"] = vehicules["obs"].replace(9, "Mobilier urbain")
vehicules["obs"] = vehicules["obs"].replace(10, "Parapet")
vehicules["obs"] = vehicules["obs"].replace(11, "Ilot, refuge, borne haute")
vehicules["obs"] = vehicules["obs"].replace(12, "Bordure de trottoir")
vehicules["obs"] = vehicules["obs"].replace(13, "Fossé, talus, paroi rocheuse")
vehicules["obs"] = vehicules["obs"].replace(14, "Autre obstacle fixe sur chaussée")
vehicules["obs"] = vehicules["obs"].replace(15, "Autre obstacle fixe sur trottoir ou accotement")
vehicules["obs"] = vehicules["obs"].replace(16, "Sortie de chaussée sans obstacle")
vehicules["obs"] = vehicules["obs"].replace(17, "Buse, tête de tunnel")

vehicules["obsm"] = vehicules["obsm"].replace(0, "Aucun")
vehicules["obsm"] = vehicules["obsm"].replace(1, "Piéton")
vehicules["obsm"] = vehicules["obsm"].replace(2, "Véhicule")
vehicules["obsm"] = vehicules["obsm"].replace(4, "Véhicule sur rail")
vehicules["obsm"] = vehicules["obsm"].replace(5, "Animal domestique")
vehicules["obsm"] = vehicules["obsm"].replace(6, "Animal sauvage")
vehicules["obsm"] = vehicules["obsm"].replace(9, "Autre")

vehicules["choc"] = vehicules["choc"].replace(0, "Aucun")
vehicules["choc"] = vehicules["choc"].replace(1, "Avant")
vehicules["choc"] = vehicules["choc"].replace(2, "Avant droit")
vehicules["choc"] = vehicules["choc"].replace(3, "Avant gauche")
vehicules["choc"] = vehicules["choc"].replace(4, "Arrière")
vehicules["choc"] = vehicules["choc"].replace(5, "Arrière droit")
vehicules["choc"] = vehicules["choc"].replace(6, "Arrière gauche")
vehicules["choc"] = vehicules["choc"].replace(7, "Côté droit")
vehicules["choc"] = vehicules["choc"].replace(8, "Côté gauche")
vehicules["choc"] = vehicules["choc"].replace(9, "Chocs multiples")

vehicules["manv"] = vehicules["manv"].replace(0, "Inconnue")
vehicules["manv"] = vehicules["manv"].replace(1, "Sans changement de direction")
vehicules["manv"] = vehicules["manv"].replace(2, "Même sens, même file")	
vehicules["manv"] = vehicules["manv"].replace(3, "Entre 2 files")
vehicules["manv"] = vehicules["manv"].replace(4, "En marche arrière")
vehicules["manv"] = vehicules["manv"].replace(5, "A contresens")
vehicules["manv"] = vehicules["manv"].replace(6, "En franchissant le terre-plein central")
vehicules["manv"] = vehicules["manv"].replace(7, "Dans le couloir bus, dans le même sens")
vehicules["manv"] = vehicules["manv"].replace(8, "Dans le couloir bus, dans le sens inverse")
vehicules["manv"] = vehicules["manv"].replace(9, "En s'insérant")
vehicules["manv"] = vehicules["manv"].replace(10, "En faisant demi-tour sur la chaussée")
vehicules["manv"] = vehicules["manv"].replace(11, "Changeant de file à gauche")
vehicules["manv"] = vehicules["manv"].replace(12, "Changeant de file à droite")
vehicules["manv"] = vehicules["manv"].replace(13, "Déporté à gauche")
vehicules["manv"] = vehicules["manv"].replace(14, "Déporté à droite")
vehicules["manv"] = vehicules["manv"].replace(15, "Tournant à gauche")
vehicules["manv"] = vehicules["manv"].replace(16, "Tournant à droite")
vehicules["manv"] = vehicules["manv"].replace(17, "Dépassant à gauche")
vehicules["manv"] = vehicules["manv"].replace(18, "Dépassant à droite")
vehicules["manv"] = vehicules["manv"].replace(19, "Traversant la chaussée")
vehicules["manv"] = vehicules["manv"].replace(20, "Manœuvre de stationnement")
vehicules["manv"] = vehicules["manv"].replace(21, "Manœuvre d'évitement")
vehicules["manv"] = vehicules["manv"].replace(22, "Ouverture de porte")
vehicules["manv"] = vehicules["manv"].replace(23, "Arrêté (hors stationnement")
vehicules["manv"] = vehicules["manv"].replace(24, "En stationnement")
vehicules["manv"] = vehicules["manv"].replace(25, "Circulant sur trottoir")
vehicules["manv"] = vehicules["manv"].replace(26, "Autres manœuvres")

vehicules["motor"] = vehicules["motor"].replace(0, "Inconnue")
vehicules["motor"] = vehicules["motor"].replace(1, "Hydrocarbures")
vehicules["motor"] = vehicules["motor"].replace(2, "Hybride Electrique")
vehicules["motor"] = vehicules["motor"].replace(3, "Electrique")
vehicules["motor"] = vehicules["motor"].replace(4, "Hydrogène")
vehicules["motor"] = vehicules["motor"].replace(5, "Humaine")
vehicules["motor"] = vehicules["motor"].replace(6, "Autre")

usagers = pd.read_csv("usagers-2022.csv", sep=";").rename(columns={"Accident_Id": "Num_Acc"})

usagers["catu"] = usagers["catu"].replace(1, "Conducteur")
usagers["catu"] = usagers["catu"].replace(2, "Passager")
usagers["catu"] = usagers["catu"].replace(3, "Piéton")

usagers["grav"] = usagers["grav"].replace(1, "Indemne")
usagers["grav"] = usagers["grav"].replace(2, "Tué")
usagers["grav"] = usagers["grav"].replace(3, "Blessé hospitalisé")
usagers["grav"] = usagers["grav"].replace(4, "Blessé léger")

usagers["sexe"] = usagers["sexe"].replace(1, "Masculin")
usagers["sexe"] = usagers["sexe"].replace(2, "Féminin")

usagers["trajet"] = usagers["trajet"].replace(0, "Non renseigné")
usagers["trajet"] = usagers["trajet"].replace(1, "Domicile - Travail")
usagers["trajet"] = usagers["trajet"].replace(2, "Domicile - Ecole")
usagers["trajet"] = usagers["trajet"].replace(3, "Courses - achats")
usagers["trajet"] = usagers["trajet"].replace(4, "Utilisation professionnelle")
usagers["trajet"] = usagers["trajet"].replace(5, "Promenade - loisirs")
usagers["trajet"] = usagers["trajet"].replace(9, "Autre")

usagers["secu1"] = usagers["secu1"].replace(0, "Aucun équipement")
usagers["secu1"] = usagers["secu1"].replace(1, "Ceinture")
usagers["secu1"] = usagers["secu1"].replace(2, "Casque")
usagers["secu1"] = usagers["secu1"].replace(3, "Gilet réfléchissant")
usagers["secu1"] = usagers["secu1"].replace(4, "Gilet réfléchissant")
usagers["secu1"] = usagers["secu1"].replace(5, "Airbag (2RM/3RM)")
usagers["secu1"] = usagers["secu1"].replace(6, "Gants (2RM/3RM)")
usagers["secu1"] = usagers["secu1"].replace(7, "Gants + Airbag(2RM/3RM)")
usagers["secu1"] = usagers["secu1"].replace(8, "Non déterminable")
usagers["secu1"] = usagers["secu1"].replace(9, "Autre")

usagers["secu2"] = usagers["secu2"].replace(0, "Aucun équipement")
usagers["secu2"] = usagers["secu2"].replace(1, "Ceinture")
usagers["secu2"] = usagers["secu2"].replace(2, "Casque")
usagers["secu2"] = usagers["secu2"].replace(3, "Dispositif enfant")
usagers["secu2"] = usagers["secu2"].replace(4, "Gilet réfléchissant")
usagers["secu2"] = usagers["secu2"].replace(5, "Airbag (2RM/3RM)")
usagers["secu2"] = usagers["secu2"].replace(6, "Gants (2RM/3RM)")
usagers["secu2"] = usagers["secu2"].replace(7, "Gants + Airbag(2RM/3RM)")
usagers["secu2"] = usagers["secu2"].replace(8, "Non déterminable")
usagers["secu2"] = usagers["secu2"].replace(9, "Autre")

usagers["secu3"] = usagers["secu3"].replace(0, "Aucun équipement")
usagers["secu3"] = usagers["secu3"].replace(1, "Ceinture")
usagers["secu3"] = usagers["secu3"].replace(2, "Casque")
usagers["secu3"] = usagers["secu3"].replace(3, "Dispositif enfant")
usagers["secu3"] = usagers["secu3"].replace(4, "Gilet réfléchissant")
usagers["secu3"] = usagers["secu3"].replace(5, "Airbag (2RM/3RM)")
usagers["secu3"] = usagers["secu3"].replace(6, "Gants (2RM/3RM)")
usagers["secu3"] = usagers["secu3"].replace(7, "Gants + Airbag(2RM/3RM)")
usagers["secu3"] = usagers["secu3"].replace(8, "Non déterminable")
usagers["secu3"] = usagers["secu3"].replace(9, "Autre")

usagers["locp"] = usagers["locp"].replace(0, "Sans objet")
usagers["locp"] = usagers["locp"].replace(1, "Sur chaussée à + 50 m du passage piéton")
usagers["locp"] = usagers["locp"].replace(2, "Sur chaussée à - 50 m du passage piéton")
usagers["locp"] = usagers["locp"].replace(3, "Sur passafe piéton et sans signalisation lumineuse")
usagers["locp"] = usagers["locp"].replace(4, "Sur passage piéton et avec signalisation lumineuse")
usagers["locp"] = usagers["locp"].replace(5, "Sur trottoir")
usagers["locp"] = usagers["locp"].replace(6, "Sur accotement")
usagers["locp"] = usagers["locp"].replace(7, "Sur refuge ou BAU")
usagers["locp"] = usagers["locp"].replace(8, "Sur contre allée")
usagers["locp"] = usagers["locp"].replace(9, "Inconnue")

usagers["actp"] = usagers["actp"].replace(0, "Se déplacant et non renseigné")
usagers["actp"] = usagers["actp"].replace(1, "Se déplaçant en Sens véhicule")
usagers["actp"] = usagers["actp"].replace(2, "Se déplaçant en Sens inverse du véhicule")
usagers["actp"] = usagers["actp"].replace(3, "Traversant")
usagers["actp"] = usagers["actp"].replace(4, "Masqué")
usagers["actp"] = usagers["actp"].replace(5, "Jouant - courant")
usagers["actp"] = usagers["actp"].replace(6, "Avec animal")
usagers["actp"] = usagers["actp"].replace(9, "Autre")
usagers["actp"] = usagers["actp"].replace("A", "Monte/Descend du véhicule")
usagers["actp"] = usagers["actp"].replace("B", "Inconnue")

usagers["etatp"] = usagers["etatp"].replace(0, "Non renseigné")
usagers["etatp"] = usagers["etatp"].replace(1, "Seul")
usagers["etatp"] = usagers["etatp"].replace(2, "Accompagné")
usagers["etatp"] = usagers["etatp"].replace(3, "En groupe")
